import java.util.ArrayList;
import java.util.List;

/**
 * Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
 * Triangle        Tn=n(n+1)/2             1, 3, 6, 10, 15, ...
 * Pentagonal      Pn=n(3n−1)/2            1, 5, 12, 22, 35, ...
 * Hexagonal       Hn=n(2n−1)              1, 6, 15, 28, 45, ...
 * It can be verified that T285 = P165 = H143 = 40755.  Find the
 * next triangle number that is also pentagonal and hexagonal.
 */
class Task45 {

  List<Long> triList = new ArrayList<>();
  List<Long> pentaList = new ArrayList<>();
  List<Long> hexList = new ArrayList<>();

  long task45Solution() {
    long answer;
    getNumbers(60000);
    for (int i = 0;  ; i++) {
      if (pentaList.contains(triList.get(i)) && hexList.contains(triList.get(i))) {
        answer = triList.get(i);
          return answer;
      }
    }
  }

  private void getNumbers(int num) {
    for (int i = 0; i < num; i++) {
      long tri = i + 286;
      long hexa = i + 144;
      long penta = i + 166;

      triList.add(tri * (tri + 1) / 2);
      pentaList.add(penta * (3 * penta - 1) / 2);
      hexList.add(hexa * (2 * hexa - 1));
    }
  }
}
